"""Banking, financial services and insurance."""

from trainjudge.domains import DomainPack

PACK = DomainPack(
    name="bfsi",
    label="BFSI",
    description="Banking, financial services and insurance",
    terms=(
        "bank",
        "banking",
        "loan",
        "loans",
        "emi",
        "kyc",
        "re-kyc",
        "aml",
        "savings account",
        "fixed deposit",
        "credit card",
        "debit card",
        "upi",
        "neft",
        "rtgs",
        "imps",
        "nach",
        "insurance",
        "premium",
        "claim",
        "claims",
        "policyholder",
        "underwriting",
        "mutual fund",
        "sip",
        "nav",
        "demat",
        "rbi",
        "sebi",
        "irdai",
        "npci",
        "nbfc",
        "fraud",
        "chargeback",
        "transaction",
        "transactions",
        "cibil",
        "credit score",
        "interest rate",
        "repo rate",
        "aeps",
        "ifsc",
        "forex",
    ),
    # Facts that move with rate resets, regulator circulars and product changes.
    changing_fact_terms=(
        "interest rate",
        "interest rates",
        "rates",
        "repo rate",
        "charges",
        "fees",
        "schedule of charges",
        "kyc norms",
        "circular",
        "circulars",
        "master direction",
        "rbi",
        "sebi",
        "irdai",
        "tds",
        "limits",
        "premium rates",
        "tariff",
    ),
    changing_facts="rate resets, revised charges, regulator circulars, new products",
    changing_fact_note=(
        "change with rate resets and circulars. Serve them from versioned documents with "
        "effective dates and citations, so every answer can be traced for audit."
    ),
    retrieval_hint=" (keep effective dates on each document)",
    high_stakes_terms=(
        "approve",
        "approval",
        "reject",
        "rejection",
        "decline",
        "credit decision",
        "loan decision",
        "underwriting decision",
        "creditworthiness",
        "credit scoring",
        "claim approval",
        "claim settlement",
        "deny claims",
        "sanction",
    ),
    high_stakes_note=(
        "Keep a human in the loop and prefer interpretable models for the decision itself. "
        "Customers may be owed reasons for adverse outcomes, and outcomes should be checked "
        "for bias across customer groups."
    ),
    closing_notes=("Keep this diagnosis and the run's EXPERIMENT_REPORT.md for model-risk review.",),
)
